### ISSUE TITLE
:gift: Contribute back OER && ETD from PALS to HYKU

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/amigos#13]
[SOW](https://github.com/scientist-softserv/amigos/issues/3)

# Summary

Contribute back ETD and OER work types.

# Acceptance Criteria

- [ ] HYKU main, by default, should have ETD and OER work types. 

# Screenshots or Video

# Testing Instructions

# Notes

**Comment by jillpe** [comment]
Blocked until Hyku 6 Release

**Comment by ShanaLMoore** [comment]
# QA Results: PASS ✅ 

Tested on: 

[Hyku DEMO](https://demo.staging.hykuup.com/dashboard/my/works?locale=en)

- [X] Hyku tenants have access to create OER and ETD work types

![Image](https://github.com/scientist-softserv/amigos/assets/10081604/a6f0f049-46f2-45f5-bf06-4a5671183cd4)




![Image](https://github.com/scientist-softserv/amigos/assets/10081604/0085001b-699d-4750-a220-c07823a50432)








- [X] a user is able to create an OER work type and attach a related item. [ref](https://demo.hyku-demo.notch8.cloud/concern/oers/5593cbe0-ec82-4f49-a47a-1936fae43299?locale=en)

<details> 



![Image](https://github.com/scientist-softserv/amigos/assets/10081604/3023d9a7-bce3-4266-b9e9-b8bf09bb2940)


</details> 

- [X] a user is able to create an ETD work type. [ref](https://demo.hyku-demo.notch8.cloud/concern/etds/81ce8a78-8501-4da1-8db8-32bb50757a94?locale=en)




</details>

**Comment by ShanaLMoore** [comment]
Update: This was my fault. I accidentally clicked OER instead of ETD 🙃 ^^ cc @kirkkwang disregard my previous comment. sorry to bother!
