### ISSUE TITLE
:gift: All the metadata in config/metadata/*_metadata.yaml needs to be translated to the m3 profile

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/amigos#15]
# Summary

Convert the schema metadata yaml files to the M3 profile format. 

Rob already did this for core metadata. After doing so, he needed to find all of the classes using core_metadata and include them in the available_on section of the M3 profile. 

Similarly, we need to create base m3 profiles for the following metadata files: 
  - [x] basic metadata (N/A)
  - [x] file set metadata
  - [x] collection metadata (N/A)
  - [x] hyrax internal metadata (N/A)
  - [x] Search through hyrax for any more metadata yaml files that may be missing from this list

Parent Ticket
- https://github.com/scientist-softserv/amigos/issues/5

Base work off of the [WIP PR](https://github.com/samvera/hyrax/pull/6830)

# Acceptance Criteria

- [ ] The following metadata schema yaml files have been converted to m3 profiles
  - [ ] basic metadata
  - [x] file set metadata
  - [ ] collection metadata
  - [ ] hyrax internal metadata

# Screenshots or Video

# Testing Instructions

# Notes
Rob already did the core metadata

**Comment by kirkkwang** [comment]
Work was done on this commit:
https://github.com/samvera/hyrax/commit/6f9935b5e427cbb20700853d645543ef61ec21ae
