### ISSUE TITLE
:gift: A copy of the m3 profile needs to be created in Dassie and Koppie that use the work types in Dassie and Koppie

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/amigos#16]
# Summary

A copy of the m3 profile needs to be created in Dassie and Koppie that use the work types in Dassie and Koppie

~Blocked by~ 
- https://github.com/scientist-softserv/amigos/issues/15

Parent Ticket
- https://github.com/scientist-softserv/amigos/issues/5

Base work off of the [WIP PR](https://github.com/samvera/hyrax/pull/6830)

# Acceptance Criteria

- [ ] Dassie and Koppie work types are included in the base m3 profiles
- [ ] confirm that the work types reflect the uploaded m3 profiles

# Screenshots or Video

# Testing Instructions

# Notes

**Comment by kirkkwang** [comment]
completed in these commits:
https://github.com/samvera/hyrax/commit/0ddbab798887adedf06f66991ce04d16b75a57d2
https://github.com/samvera/hyrax/commit/42fca417795d7f790f65d1bc4e1b1562a72bbd1d
https://github.com/samvera/hyrax/commit/f186c18173dca8b9a3122bbd5c1ffbd692478aa8
https://github.com/samvera/hyrax/commit/f186c18173dca8b9a3122bbd5c1ffbd692478aa8
https://github.com/samvera/hyrax/commit/bcaf5ab9f653c1deab320360eaa270b6529bbb1a
