### ISSUE TITLE
:gift: Loading the default profile should be added to the seeds if the flag is turned on for now (since an uploading interface is down the road)

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/amigos#17]
# Summary

Seeds should load the default m3 profiles if the feature flag (env variable) is turned on.

Blocked by: 
- #15 

Parent Ticket
- https://github.com/scientist-softserv/amigos/issues/5

Base work off of the [WIP PR](https://github.com/samvera/hyrax/pull/6830)

# Acceptance Criteria

- [ ] Running seeds will load the default m3 profiles

# Screenshots or Video

# Testing Instructions

# Notes

**Comment by orangewolf** [comment]
@ShanaLMoore I don't see why this would need to be blocked by adding all the metadata. I did it in order to test the work I was doing. Should work for both apps because of the way Hyrax is built.

**Comment by ShanaLMoore** [comment]
Great! We noticed you finished this so I'm going to close it then.
