### ISSUE TITLE
✅ Specs for SchemaLoader need to be done

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/amigos#18]
# Summary

The SimpleSchemaLoader and M3SchemaLoader were refactored to inherit from the SchemaLoader.  Add specs for the Hyrax::SchemaLoader class and its children if applicable.

Parent Ticket
- https://github.com/scientist-softserv/amigos/issues/5

Base work off of the [WIP PR](https://github.com/samvera/hyrax/pull/6830)

# Acceptance Criteria

- [ ] Hyrax::\SchemaLoader has spec coverage

# Screenshots or Video

# Testing Instructions

# Notes

**Comment by kirkkwang** [comment]
Handled in this commit https://github.com/samvera/hyrax/commit/44b75f9656cd610a34707af97a9aa7ba9158831b
