### ISSUE TITLE
✅ Specs for Hyrax::FlexibleSchema need to be done

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/amigos#19]
# Summary

Add specs for the Hyrax::FlexibleSchema class

Parent Ticket
- https://github.com/scientist-softserv/amigos/issues/5

Base work off of the [WIP PR](https://github.com/samvera/hyrax/pull/6830)

# Acceptance Criteria

- [ ] Hyrax::FlexibleSchema has spec coverage 

# Screenshots or Video

# Testing Instructions

# Notes

**Comment by ShanaLMoore** [comment]
TODO: since Rob was still developing, please recheck the coverage is adequate cc @kirkkwang

**Comment by kirkkwang** [comment]
Handled in this commit https://github.com/samvera/hyrax/commit/797a48da83a88fd076e570785b919b249d259876
