### ISSUE TITLE
✅ Spec coverage for Hyrax::Resource with dynamic loading need to be written

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/amigos#20]
# Summary

Add specs that covers dynamic loading for Hyrax::Resource 

Parent Ticket
- https://github.com/scientist-softserv/amigos/issues/5

Base work off of the [WIP PR](https://github.com/samvera/hyrax/pull/6830)

# Acceptance Criteria

- [ ] Changes to Hyrax::Resource has spec coverage for dynamic loading

# Screenshots or Video

# Testing Instructions

# Notes

**Comment by ShanaLMoore** [comment]
[This](https://github.com/samvera/hyrax/pull/6830/commits/6209db7e119d42d5b5c258c71c16923afdfcfd71) will test that the module is included. ✅ 

We also need to test the module itself.
- #25

**Comment by ShanaLMoore** [comment]
TODO: since Rob was still developing, please recheck the coverage is adequate cc @kirkkwang

**Comment by kirkkwang** [comment]
Handled in this commit https://github.com/samvera/hyrax/commit/44b75f9656cd610a34707af97a9aa7ba9158831b

**Comment by kirkkwang** [comment]
Reverted the spec in this commit https://github.com/samvera/hyrax/commit/4275dbce53f44f336ac2964bf3f02b3bfa1c3d9a

The spec was causing flaky issues and really felt unnecessary because it was simply testing an if statement
