### ISSUE TITLE
:gift: Indexing Object Dynamic Loading

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/amigos#21]
# Summary

 Indexing object dynamic loading needs to be figured out

# Acceptance Criteria

# Testing Instructions

**Comment by kirkkwang** [comment]
work was handled in these commits
https://github.com/samvera/hyrax/commit/6542b0d64081e2e940b1706ea7ca843189ecf6e9
https://github.com/samvera/hyrax/commit/9115944ba308eb32b2fc427016336cd5a4bde798
