### ISSUE TITLE
✅ Specs for Hyrax::Flexibility

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/amigos#25]
# Summary

Add specs for the Hyrax::Flexibility class

Parent Ticket
- https://github.com/scientist-softserv/amigos/issues/5

Base work off of the [WIP PR](https://github.com/samvera/hyrax/pull/6830)

# Acceptance Criteria

- [ ] Hyrax::Flexibility has spec coverage

# Screenshots or Video

# Testing Instructions

# Notes

**Comment by kirkkwang** [comment]
Handled in this https://github.com/samvera/hyrax/commit/4f0688004ce5a4814a371c2a4cb42474141f26a6

**Comment by kirkkwang** [comment]
Handled in this https://github.com/samvera/hyrax/commit/4f0688004ce5a4814a371c2a4cb42474141f26a6
