### ISSUE TITLE
🎁 Implement UI to upload yamls

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/amigos#9]
[SOW](https://github.com/scientist-softserv/amigos/issues/1)

# Summary

Allinson Flex provides a UI that allows users to upload their metadata schema YAML files. Once imported, the models will behave according to the definitions in the YAML files.

For Valkyrie/Hyrax, currently, the YAML files must be predefined and deployed. This UI will enable non-developers to define or change their application's models.

The backend work is covered by #5.

This task focuses solely on the frontend work, which should be contributed back to Hyrax.

# Acceptance Criteria

A user can upload metadata profiles from a UI.
The UI shouldn't display if the `HYRAX_FLEXIBLE` env var isn't set

# Screenshots or Video

# Testing Instructions

# Notes

**Comment by ShanaLMoore** [comment]
boiler plate started on Hyrax branch: [metadata-profiles-ui ](https://github.com/samvera/hyrax/compare/double_combo...metadata-profiles-ui?expand=1). I pulled over the necessary files from AllinsonFlex. We will still need to add actions and hooks into the backend implementation to make it work. 

**Blocked** from completion until back end work is further along.




![Image](https://github.com/scientist-softserv/amigos/assets/10081604/751cde3e-2b11-4bc9-9e91-5598ca3a4cc7)



## Allinson Flex UI


![Image](https://github.com/scientist-softserv/amigos/assets/10081604/f59d0cfb-b205-4b6e-9e03-4050edd514c3)

**Comment by kirkkwang** [comment]
Work done on this PR: https://github.com/samvera/hyrax/pull/6836
